name: Sync to personal repo 4cores on master push

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        

      - name: Debug Token Input
        run: |
          echo "Using token for user: 4-Cores"
          # DO NOT PRINT THE FULL TOKEN. Instead, print a masked version or its length.
          TOKEN_VALUE="${{ secrets.PUSH_TOKEN }}"
          echo "Token starts with: ${TOKEN_VALUE:0:5} and ends with: ${TOKEN_VALUE: -5}"
          echo "Token length: ${#TOKEN_VALUE}"
        

      - name: Push to destination
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add destination https://ALPHA-1503:${{ secrets.PUSH_TOKEN }}@github.com/ALPHA-1503/test-cloning.git
          git push destination master --force
