name: Sync to personal repo 4cores on master push

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        
        
      - name: Debug secret (NE PAS LAISSER EN PROD)
        run: echo "Token:" ${{ secrets.UPDATE_REPO }}

        
      - name: Push to destination repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add r2 https://x-access-token:${{ secrets.UPDATE_REPO }}@github.com/ALPHA-1503/test-cloning.git
          git push --force r2 master
