name: Push to ALPHA-1503/4cores repo

on:
  push:
    branches:
      - master

jobs:
  push-to-public:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Push to public repo
        run: |
          git remote add public https://x-access-token:${{ secrets.VERCEL_REPO_4CORES }}@github.com/ALPHA-1503/test-cloning.git
          git push public master --force
